CREATE TABLE FarmerMarkets (
    FMID INT NOT NULL,
    MarketName VARCHAR(255) NULL,
    Website VARCHAR(255) NULL,
    Facebook VARCHAR(255) NULL,
    Twitter VARCHAR(255) NULL,
    Youtube VARCHAR(255) NULL,
    OtherMedia VARCHAR(255) NULL,
    street VARCHAR(255) NULL,
    city VARCHAR(255) NULL,
    County VARCHAR(255) NULL,
    State VARCHAR(255) NULL,
    zip VARCHAR(255) NULL,
    Season1Date VARCHAR(255) NULL,
    Season1Time VARCHAR(255) NULL,
    Season2Date VARCHAR(255) NULL,
    Season2Time VARCHAR(255) NULL,
    Season3Date VARCHAR(255) NULL,
    Season3Time VARCHAR(255) NULL,
    Season4Date VARCHAR(255) NULL,
    Season4Time VARCHAR(255) NULL,
    x VARCHAR(255) NULL,
    y VARCHAR(255) NULL,
    Location VARCHAR(255) NULL,
    Credit VARCHAR(255) NULL,
    WIC VARCHAR(255) NULL,
    WICcash VARCHAR(255) NULL,
    SFMNP VARCHAR(255) NULL,
    SNAP VARCHAR(255) NULL,
    Organic VARCHAR(255) NULL,
    Bakedgoods VARCHAR(255) NULL,
    Cheese VARCHAR(255) NULL,
    Crafts VARCHAR(255) NULL,
    Flowers VARCHAR(255) NULL,
    Eggs VARCHAR(255) NULL,
    Seafood VARCHAR(255) NULL,
    Herbs VARCHAR(255) NULL,
    Vegetables VARCHAR(255) NULL,
    Honey VARCHAR(255) NULL,
    Jams VARCHAR(255) NULL,
    Maple VARCHAR(255) NULL,
    Meat VARCHAR(255) NULL,
    Nursery VARCHAR(255) NULL,
    Nuts VARCHAR(255) NULL,
    Plants VARCHAR(255) NULL,
    Poultry VARCHAR(255) NULL,
    Prepared VARCHAR(255) NULL,
    Soap VARCHAR(255) NULL,
    Trees VARCHAR(255) NULL,
    Wine VARCHAR(255) NULL,
    Coffee VARCHAR(255) NULL,
    Beans VARCHAR(255) NULL,
    Fruits VARCHAR(255) NULL,
    Grains VARCHAR(255) NULL,
    Juices VARCHAR(255) NULL,
    Mushrooms VARCHAR(255) NULL,
    PetFood VARCHAR(255) NULL,
    Tofu VARCHAR(255) NULL,
    WildHarvested VARCHAR(255) NULL,
    updateTime VARCHAR(255) NULL,
    PRIMARY KEY(FMID)
);

LOAD DATA LOCAL INFILE '/Users/denis/ITMO/Python/Exercises/Export.csv' 
INTO TABLE FarmerMarkets FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS (
    FMID, 
    MarketName, 
    Website, 
    Facebook, 
    Twitter, 
    Youtube, 
    OtherMedia, 
    street, 
    city, 
    County, 
    State, 
    zip, 
    Season1Date, 
    Season1Time, 
    Season2Date, 
    Season2Time, 
    Season3Date, 
    Season3Time, 
    Season4Date, 
    Season4Time, 
    x, 
    y, 
    Location, 
    Credit, 
    WIC, 
    WICcash, 
    SFMNP, 
    SNAP, 
    Organic, 
    Bakedgoods, 
    Cheese, 
    Crafts, 
    Flowers, 
    Eggs, 
    Seafood, 
    Herbs, 
    Vegetables, 
    Honey, 
    Jams, 
    Maple, 
    Meat, 
    Nursery, 
    Nuts, 
    Plants, 
    Poultry, 
    Prepared, 
    Soap, 
    Trees, 
    Wine, 
    Coffee, 
    Beans, 
    Fruits, 
    Grains, 
    Juices, 
    Mushrooms, 
    PetFood, 
    Tofu, 
    WildHarvested, 
    updateTime
);

CREATE TABLE Users (
    EmailID VARCHAR(200) NOT NULL PRIMARY KEY,
    UserName VARCHAR(200) NOT NULL,
    Password VARCHAR(200) NOT NULL
);

CREATE TABLE Reviews (
    ReviewID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ReviewText VARCHAR(500) NULL,
    Rating INT NOT NULL,
    MarketID INT,
    UserEmail VARCHAR(200),
    FOREIGN KEY (MarketID) REFERENCES FarmerMarkets(FMID),
    FOREIGN KEY (UserEmail) REFERENCES Users(EmailID)
);


